from enum import Enum

class ProjectType(Enum):
    PYTHON = "python"
    JAVA = "java"
    CSHARP = "csharp"
    JAVASCRIPT = "javascript"
    TYPESCRIPT = "typescript"
    GO = "go"
    RUST = "rust"
    CPP = "cpp"          # C++
    C = "c"
    SWIFT = "swift"
    KOTLIN = "kotlin"
    RUBY = "ruby"
    PHP = "php"
    DART = "dart"
    LUA = "lua"
    ROBLOX_LUA = "roblox_lua"
    R = "r"
    HASKELL = "haskell"
    ELIXIR = "elixir"
    SCALA = "scala"
    PERL = "perl"
    SHELL = "shell"
    POWERSHELL = "powershell"
    SQL = "sql"
    HTML = "html"
    CSS = "css"
    JSON = "json"
    YAML = "yaml"
    MARKDOWN = "markdown"
    TEX = "latex"        # LaTeX
    ASSEMBLY = "assembly"
    V = "vlang"
    ZIG = "zig"
    CRYSTAL = "crystal"
